#pragma once
#include "hid_device_key.h"
#include "layout.h"

extern const layout_image_t layout_us_normal;
extern const layout_image_t layout_us_active;

static const layout_input_t layout_inputs[] = {
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 0, 0, 92, 60 }, .key = HID_DEVICE_KEY_ESCAPE },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 92, 0, 91, 60 }, .key = HID_DEVICE_KEY_F1 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 183, 0, 92, 60 }, .key = HID_DEVICE_KEY_F2 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 275, 0, 91, 60 }, .key = HID_DEVICE_KEY_F3 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 366, 0, 91, 60 }, .key = HID_DEVICE_KEY_F4 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 457, 0, 92, 60 }, .key = HID_DEVICE_KEY_F5 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 549, 0, 91, 60 }, .key = HID_DEVICE_KEY_F6 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 640, 0, 91, 60 }, .key = HID_DEVICE_KEY_F7 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 731, 0, 92, 60 }, .key = HID_DEVICE_KEY_F8 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 823, 0, 91, 60 }, .key = HID_DEVICE_KEY_F9 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 914, 0, 91, 60 }, .key = HID_DEVICE_KEY_F10 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1005, 0, 92, 60 }, .key = HID_DEVICE_KEY_F11 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1097, 0, 91, 60 }, .key = HID_DEVICE_KEY_F12 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1188, 0, 92, 60 }, .key = HID_DEVICE_KEY_DELETE },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 0, 60, 89, 80 }, .key = HID_DEVICE_KEY_GRAVE },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 89, 60, 89, 80 }, .key = HID_DEVICE_KEY_1 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 178, 60, 89, 80 }, .key = HID_DEVICE_KEY_2 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 267, 60, 89, 80 }, .key = HID_DEVICE_KEY_3 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 356, 60, 89, 80 }, .key = HID_DEVICE_KEY_4 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 445, 60, 89, 80 }, .key = HID_DEVICE_KEY_5 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 534, 60, 89, 80 }, .key = HID_DEVICE_KEY_6 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 623, 60, 89, 80 }, .key = HID_DEVICE_KEY_7 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 712, 60, 89, 80 }, .key = HID_DEVICE_KEY_8 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 801, 60, 89, 80 }, .key = HID_DEVICE_KEY_9 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 890, 60, 89, 80 }, .key = HID_DEVICE_KEY_0 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 979, 60, 89, 80 }, .key = HID_DEVICE_KEY_MINUS },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1068, 60, 89, 80 }, .key = HID_DEVICE_KEY_EQUAL },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1157, 60, 123, 80 }, .key = HID_DEVICE_KEY_BACKSPACE },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 0, 140, 123, 80 }, .key = HID_DEVICE_KEY_TAB },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 123, 140, 89, 80 }, .key = HID_DEVICE_KEY_Q },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 212, 140, 89, 80 }, .key = HID_DEVICE_KEY_W },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 301, 140, 89, 80 }, .key = HID_DEVICE_KEY_E },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 390, 140, 89, 80 }, .key = HID_DEVICE_KEY_R },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 479, 140, 89, 80 }, .key = HID_DEVICE_KEY_T },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 568, 140, 89, 80 }, .key = HID_DEVICE_KEY_Y },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 657, 140, 89, 80 }, .key = HID_DEVICE_KEY_U },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 746, 140, 89, 80 }, .key = HID_DEVICE_KEY_I },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 835, 140, 89, 80 }, .key = HID_DEVICE_KEY_O },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 924, 140, 89, 80 }, .key = HID_DEVICE_KEY_P },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1013, 140, 89, 80 }, .key = HID_DEVICE_KEY_LEFT_BRACKET },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1102, 140, 89, 80 }, .key = HID_DEVICE_KEY_RIGHT_BRACKET },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1191, 140, 89, 80 }, .key = HID_DEVICE_KEY_BACKSLASH },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 0, 220, 150, 80 }, .key = HID_DEVICE_KEY_CAPS_LOCK },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 150, 220, 89, 80 }, .key = HID_DEVICE_KEY_A },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 239, 220, 89, 80 }, .key = HID_DEVICE_KEY_S },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 328, 220, 89, 80 }, .key = HID_DEVICE_KEY_D },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 417, 220, 89, 80 }, .key = HID_DEVICE_KEY_F },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 506, 220, 89, 80 }, .key = HID_DEVICE_KEY_G },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 595, 220, 89, 80 }, .key = HID_DEVICE_KEY_H },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 684, 220, 89, 80 }, .key = HID_DEVICE_KEY_J },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 773, 220, 89, 80 }, .key = HID_DEVICE_KEY_K },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 862, 220, 89, 80 }, .key = HID_DEVICE_KEY_L },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 951, 220, 89, 80 }, .key = HID_DEVICE_KEY_SEMICOLON },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1040, 220, 89, 80 }, .key = HID_DEVICE_KEY_QUOTE },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1129, 220, 151, 80 }, .key = HID_DEVICE_KEY_ENTER },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 0, 300, 195, 80 }, .key = HID_DEVICE_KEY_LEFT_SHIFT },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 195, 300, 89, 80 }, .key = HID_DEVICE_KEY_Z },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 284, 300, 89, 80 }, .key = HID_DEVICE_KEY_X },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 373, 300, 89, 80 }, .key = HID_DEVICE_KEY_C },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 462, 300, 89, 80 }, .key = HID_DEVICE_KEY_V },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 551, 300, 89, 80 }, .key = HID_DEVICE_KEY_B },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 640, 300, 89, 80 }, .key = HID_DEVICE_KEY_N },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 729, 300, 89, 80 }, .key = HID_DEVICE_KEY_M },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 818, 300, 89, 80 }, .key = HID_DEVICE_KEY_COMMA },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 907, 300, 89, 80 }, .key = HID_DEVICE_KEY_DOT },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 996, 300, 89, 80 }, .key = HID_DEVICE_KEY_SLASH },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1085, 300, 195, 80 }, .key = HID_DEVICE_KEY_RIGHT_SHIFT },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 0, 380, 112, 80 }, .key = HID_DEVICE_KEY_LEFT_CTRL },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 112, 380, 112, 80 }, .key = HID_DEVICE_KEY_LEFT_GUI },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 224, 380, 112, 80 }, .key = HID_DEVICE_KEY_LEFT_ALT },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 336, 380, 608, 80 }, .key = HID_DEVICE_KEY_SPACE },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 944, 380, 112, 80 }, .key = HID_DEVICE_KEY_RIGHT_ALT },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1056, 380, 112, 80 }, .key = HID_DEVICE_KEY_RIGHT_GUI },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1168, 380, 112, 80 }, .key = HID_DEVICE_KEY_RIGHT_CTRL },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 916, 619, 114, 81 }, .key = HID_DEVICE_KEY_LEFT },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 1146, 619, 114, 81 }, .key = HID_DEVICE_KEY_RIGHT },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 916, 539, 116, 80 }, .key = HID_DEVICE_KEY_UP },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 916, 620, 116, 80 }, .key = HID_DEVICE_KEY_UP },
    { .type = LAYOUT_INPUT_TYPE_TRACKPAD, .region = { 384, 460, 512, 260 } },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 20, 600, 172, 100 }, .key = HID_DEVICE_KEY_MOUSE_BUTTON_1 },
    { .type = LAYOUT_INPUT_TYPE_KEY, .region = { 192, 600, 172, 100 }, .key = HID_DEVICE_KEY_MOUSE_BUTTON_2 },
};
static const layout_config_t layout_config = {
    .title = "1. US",
    .base_image = &layout_us_normal,
    .active_image = &layout_us_active,
    .inputs = layout_inputs,
    .count = 81,
};
LAYOUT_REGISTER(layout_config)
